export const hospitals = [
  {
    id: "1",
    name: "Memorial Hospital",
    location: "123 Main Street, Anytown USA",
    phone: "555-555-5555",
    city: "rajshahi",
    place: "Madina-Market",
    thumbnail: "/images/hospitals/hospital-1.png",
    tests: [
      { name: "COVID-19", price: 100 },
      { name: "influenza", price: 25 },
      { name: "allergy", price: 50 },
      { name: "ear test", price: 75 },
      { name: "x-ray", price: 150 },
      { name: "ECG", price: 200 },
      { name: "MRI", price: 500 },
      { name: "CT scan", price: 400 },
      { name: "blood test", price: 75 },
      { name: "pregnancy test", price: 50 },
      { name: "HIV test", price: 100 },
      { name: "urine test", price: 25 },
      { name: "bone density test", price: 100 },
      { name: "DNA test", price: 500 },
      { name: "tumor marker test", price: 200 },
      { name: "cholesterol test", price: 75 },
    ],
    services: [
      "emergency care",
      "surgery",
      "physical therapy",
      "cardiology",
      "oncology",
      "gynecology",
      "dermatology",
      "neurology",
      "orthopedics",
      "ENT",
      "ophthalmology",
      "pediatrics",
      "psychiatry",
      "radiology",
      "urology",
    ],
    hours: "24/7",
    about:
      "Memorial Hospital is a state-of-the-art healthcare facility located in Anytown USA. We offer a wide range of medical services and tests to meet the needs of our patients. Our dedicated team of medical professionals is committed to providing high-quality, compassionate care to everyone who walks through our doors. We are open 24/7 to serve our community.",
    supportEmail: "support@memorialhospital.com",
  },
  {
    id: "2",
    name: "Anytown Hospital",
    location: "123 Main Street, Anytown USA",
    phone: "555-555-5555",
    city: "dhaka",
    place: "Madina-Market",
    thumbnail: "/images/hospitals/hospital-2.png",
    tests: [
      { name: "COVID-19", price: 100 },
      { name: "influenza", price: 25 },
      { name: "allergy", price: 50 },
      { name: "ear test", price: 75 },
      { name: "x-ray", price: 150 },
      { name: "ECG", price: 200 },
      { name: "MRI", price: 500 },
      { name: "CT scan", price: 400 },
      { name: "blood test", price: 75 },
      { name: "pregnancy test", price: 50 },
      { name: "HIV test", price: 100 },
      { name: "urine test", price: 25 },
      { name: "bone density test", price: 100 },
      { name: "DNA test", price: 500 },
      { name: "tumor marker test", price: 200 },
      { name: "cholesterol test", price: 75 },
    ],
    services: [
      "emergency care",
      "surgery",
      "physical therapy",
      "cardiology",
      "oncology",
      "gynecology",
      "dermatology",
      "neurology",
      "orthopedics",
      "ENT",
      "ophthalmology",
      "pediatrics",
      "psychiatry",
      "radiology",
      "urology",
    ],
    hours: "24/7",
    about:
      "Anytown Hospital is a state-of-the-art healthcare facility located in Anytown USA. We offer a wide range of medical services and tests to meet the needs of our patients. Our dedicated team of medical professionals is committed to providing high-quality, compassionate care to everyone who walks through our doors. We are open 24/7 to serve our community.",
    supportEmail: "support@anytownhospital.com",
  },
  {
    id: "3",
    name: "Anytown Medical Center",
    location: "123 Main Street, Anytown USA",
    city: "chittagong",
    phone: "555-555-5555",
    thumbnail: "/images/hospitals/hospital-3.png",
    place: "Madina-Market",
    tests: [
      { name: "COVID-19", price: 100 },
      { name: "influenza", price: 25 },
      { name: "allergy", price: 50 },
      { name: "ear test", price: 75 },
      { name: "x-ray", price: 150 },
      { name: "ECG", price: 200 },
      { name: "MRI", price: 500 },
      { name: "CT scan", price: 400 },
      { name: "blood test", price: 75 },
      { name: "pregnancy test", price: 50 },
      { name: "HIV test", price: 100 },
      { name: "urine test", price: 25 },
      { name: "bone density test", price: 100 },
      { name: "DNA test", price: 500 },
      { name: "tumor marker test", price: 200 },
      { name: "cholesterol test", price: 75 },
    ],
    services: [
      "emergency care",
      "surgery",
      "physical therapy",
      "cardiology",
      "oncology",
      "gynecology",
      "dermatology",
      "neurology",
      "orthopedics",
      "ENT",
      "ophthalmology",
      "pediatrics",
      "psychiatry",
      "radiology",
      "urology",
    ],
    hours: "24/7",
    about:
      "Anytown Medical Center is a state-of-the-art healthcare facility located in Anytown USA. We offer a wide range of medical services and tests to meet the needs of our patients. Our dedicated team of medical professionals is committed to providing high-quality, compassionate care to everyone who walks through our doors. We are open 24/7 to serve our community.",
    supportEmail: "support@anytownmedical.com",
  },
  {
    id: "4",
    name: "Anytown General Hospital",
    location: "123 Main Street, Anytown USA",
    city: "sylhet",
    place: "Madina-Market",
    phone: "555-555-5555",
    thumbnail: "/images/hospitals/hospital-1.png",
    tests: [
      { name: "COVID-19", price: 100 },
      { name: "influenza", price: 25 },
      { name: "allergy", price: 50 },
      { name: "ear test", price: 75 },
      { name: "x-ray", price: 150 },
      { name: "ECG", price: 200 },
      { name: "MRI", price: 500 },
      { name: "CT scan", price: 400 },
      { name: "blood test", price: 75 },
      { name: "pregnancy test", price: 50 },
      { name: "HIV test", price: 100 },
      { name: "urine test", price: 25 },
      { name: "bone density test", price: 100 },
      { name: "DNA test", price: 500 },
      { name: "tumor marker test", price: 200 },
      { name: "cholesterol test", price: 75 },
    ],
    services: [
      "emergency care",
      "surgery",
      "physical therapy",
      "cardiology",
      "oncology",
      "gynecology",
      "dermatology",
      "neurology",
      "orthopedics",
      "ENT",
      "ophthalmology",
      "pediatrics",
      "psychiatry",
      "radiology",
      "urology",
    ],
    hours: "24/7",
    about:
      "Anytown Medical Center is a state-of-the-art healthcare facility located in Anytown USA. We offer a wide range of medical services and tests to meet the needs of our patients. Our dedicated team of medical professionals is committed to providing high-quality, compassionate care to everyone who walks through our doors. We are open 24/7 to serve our community.",
    supportEmail: "support@anytownmedical.com",
  },
  {
    id: "5",
    name: "Anytown Medical Center",
    location: "123 Main Street, Anytown USA",
    city: "khulna",
    place: "Madina-Market",
    phone: "555-555-5555",
    thumbnail: "/images/hospitals/hospital-2.png",
    tests: [
      { name: "COVID-19", price: 100 },
      { name: "influenza", price: 25 },
      { name: "allergy", price: 50 },
      { name: "ear test", price: 75 },
      { name: "x-ray", price: 150 },
      { name: "ECG", price: 200 },
      { name: "MRI", price: 500 },
      { name: "CT scan", price: 400 },
      { name: "blood test", price: 75 },
      { name: "pregnancy test", price: 50 },
      { name: "HIV test", price: 100 },
      { name: "urine test", price: 25 },
      { name: "bone density test", price: 100 },
      { name: "DNA test", price: 500 },
      { name: "tumor marker test", price: 200 },
      { name: "cholesterol test", price: 75 },
    ],
    services: [
      "emergency care",
      "surgery",
      "physical therapy",
      "cardiology",
      "oncology",
      "gynecology",
      "dermatology",
      "neurology",
      "orthopedics",
      "ENT",
      "ophthalmology",
      "pediatrics",
      "psychiatry",
      "radiology",
      "urology",
    ],
    hours: "24/7",
    about:
      "Anytown Medical Center is a state-of-the-art healthcare facility located in Anytown USA. We offer a wide range of medical services and tests to meet the needs of our patients. Our dedicated team of medical professionals is committed to providing high-quality, compassionate care to everyone who walks through our doors. We are open 24/7 to serve our community.",
    supportEmail: "support@anytownmedical.com",
  },
  {
    id: "6",
    name: "Anytown General Hospital",
    location: "123 Main Street, Anytown USA",
    city: "sylhet",
    place: "Madina-Market",
    phone: "555-555-5555",
    thumbnail: "/images/hospitals/hospital-1.png",
    tests: [
      { name: "COVID-19", price: 100 },
      { name: "influenza", price: 25 },
      { name: "allergy", price: 50 },
      { name: "ear test", price: 75 },
      { name: "x-ray", price: 150 },
      { name: "ECG", price: 200 },
      { name: "MRI", price: 500 },
      { name: "CT scan", price: 400 },
      { name: "blood test", price: 75 },
      { name: "pregnancy test", price: 50 },
      { name: "HIV test", price: 100 },
      { name: "urine test", price: 25 },
      { name: "bone density test", price: 100 },
      { name: "DNA test", price: 500 },
      { name: "tumor marker test", price: 200 },
      { name: "cholesterol test", price: 75 },
    ],
    services: [
      "emergency care",
      "surgery",
      "physical therapy",
      "cardiology",
      "oncology",
      "gynecology",
      "dermatology",
      "neurology",
      "orthopedics",
      "ENT",
      "ophthalmology",
      "pediatrics",
      "psychiatry",
      "radiology",
      "urology",
    ],
    hours: "24/7",
    about:
      "Anytown Medical Center is a state-of-the-art healthcare facility located in Anytown USA. We offer a wide range of medical services and tests to meet the needs of our patients. Our dedicated team of medical professionals is committed to providing high-quality, compassionate care to everyone who walks through our doors. We are open 24/7 to serve our community.",
    supportEmail: "support@anytownmedical.com",
  },
];
